services:
  postgres:
    image: postgres:16
    container_name: ai-board-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: KJ
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: aiboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: