ALTER TABLE "PostRagDocument"
  ADD COLUMN "title" VARCHAR(200) NOT NULL DEFAULT '',
  ADD COLUMN "author" VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN "postUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "contentSummary" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "ingredients" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "ingredientAliases" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "dishNames" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "cookingMethods" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "situationTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "difficulty" VARCHAR(40) NOT NULL DEFAULT '미정',
  ADD COLUMN "cookingTime" VARCHAR(40) NOT NULL DEFAULT '미정',
  ADD COLUMN "popularityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "searchableText" TEXT NOT NULL DEFAULT '';

CREATE TABLE "BoardRagChatLog" (
  "id" SERIAL PRIMARY KEY,
  "userMessage" TEXT NOT NULL,
  "extractedIngredients" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "retrievedPostIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  "selectedPostIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  "scores" JSONB NOT NULL,
  "answerText" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
